    <?php
    $env = parse_ini_file('../.env');
    $host     = 'localhost';
    $db       = 'simbio';
    $user     = $env['db_user'];
    $password = $env['db_password'];
    $charset  = 'utf8mb4';

    $dsn = "mysql:host=$host;dbname=$db;charset=$charset";

    try {
        // Conexión PDO
        $pdo = new PDO($dsn, $user, $password, [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]);

        echo "Conectado a la base de datos...\n";

        $sql = <<<SQL
        INSERT INTO tag (tag_id, name, parent_id) VALUES 
        (1, 'AF', NULL),
        (2, 'AG', NULL),
        (3, 'AR', NULL),
        (4, 'CM', NULL),
        (5, 'EA', NULL),
        (6, 'EE', NULL),
        (7, 'EO', NULL),
        (8, 'FM', NULL),
        (9, 'FS', NULL),
        (10, 'HT', NULL),
        (11, 'IA', NULL),
        (12, 'IC', NULL),
        (13, 'IE', NULL),
        (14, 'IM', NULL),
        (15, 'IP', NULL),
        (16, 'IS', NULL),
        (17, 'MP', NULL),
        (18, 'QU', NULL),
        (19, 'SA', NULL),
        (20, 'SC', NULL),
        (21, 'SM', NULL),
        (22, 'TM', NULL),
        (23, 'TX', NULL),
        (24, 'AE', NULL),
        (25, 'SE', NULL),
        (26, 'Preimpressió digital', 1),
        (27, 'Impressió gràfica', 1),
        (28, 'Postimpressió i acabats gràfics', 1),
        (29, 'Disseny i edició de publicacions impreses i multimèdia', 1),
        (30, 'Disseny i gestió de la producció gràfica', 1),
        (31, 'Conducció d''activitats fisicoesportives en el medi natural', 1),
        (32, 'Animació d''activitats físiques i esportives', 1),
        (33, 'Gestió administrativa', 2),
        (34, 'Assistència a la direcció', 2),
        (35, 'Administració i finances', 2),
        (36, 'Producció agropecuària', 3),
        (37, 'Producció agroecològica', 3),
        (38, 'Aprofitament i conservació del medi natural', 3),
        (39, 'Jardineria i floristeria', 3),
        (40, 'Activitats eqüestres', 3),
        (41, 'Gestió forestal i del medi natural', 3),
        (42, 'Paisatgisme i medi rural', 3),
        (43, 'Ramaderia i assistència en sanitat animal', 3),
        (44, 'Gestió de vendes i espais comercials', 4),
        (45, 'Comerç internacional', 4),
        (46, 'Transport i logística', 4),
        (47, 'Màrqueting i publicitat', 4),
        (48, 'Serveis al consumidor', 4),
        (49, 'Activitats comercials', 4),
        (50, 'Xarxes, instal·lacions i estacions de tractament d''aigua', 5),
        (51, 'Xarxes i estacions de tractament d''aigües', 5),
        (52, 'Eficiència energètica i energia solar tèrmica', 5),
        (53, 'Energies renovables', 5),
        (54, 'Gestió de l''aigua', 5),
        (55, 'Instal·lacions elèctriques i automàtiques', 6),
        (56, 'Instal.lacions de telecomunicacions', 6),
        (57, 'Sistemes electrotècnics i automatitzats', 6),
        (58, 'Automatització i robòtica industrial', 6),
        (59, 'Manteniment electrònic', 6),
        (60, 'Sistemes de telecomunicacions i informàtics', 6),
        (61, 'Electromedicina clínica', 6),
        (62, 'Obres d''interior, decoració i rehabilitació', 7),
        (63, 'Construcció', 7),
        (64, 'Projectes d''obra civil', 7),
        (65, 'Projectes d''edificació', 7),
        (66, 'Organització i control d''obres de construcció', 7),
        (67, 'Realització i plans d''obres', 7),
        (68, 'Soldadura i caldereria', 8),
        (69, 'Mecanització', 8),
        (70, 'Construccions metàl·liques', 8),
        (71, 'Programació de la producció en fabricación mecànica', 8),
        (72, 'Disseny en fabricació mecànica', 8),
        (73, 'Programació de la producció en emmotllament de metalls i polímers', 8),
        (74, 'Fusteria i moble', 9),
        (75, 'Instal·lació i moblament', 9),
        (76, 'Disseny i moblament', 9),
        (77, 'Cuina i gastronomia', 10),
        (78, 'Serveis en restauració', 10),
        (79, 'Agències de viatges i gestió d''esdeveniments', 10),
        (80, 'Gestió d''allotjaments turístics', 10),
        (81, 'Direcció de cuina', 10),
        (82, 'Direcció de serveis en restauració', 10),
        (83, 'Guia, informació i assistència turístiques', 10),
        (84, 'Elaboració de productes alimentaris', 11),
        (85, 'Olis d''oliva i vins', 11),
        (86, 'Forneria, pastisseria i confiteria', 11),
        (87, 'Vitivinicultura', 11),
        (88, 'Processos i qualitat en la indústria alimentària', 11),
        (89, 'Sistemes microinformàtics i xarxes', 12),
        (90, 'Administració de sistemes informàtics en xarxa', 12),
        (91, 'Desenvolupament d''aplicacions multiplataforma', 12),
        (92, 'Desenvolupament d''aplicacions web', 12),
        (93, 'Excavacions i sondatges', 13),
        (94, 'Pedra natural', 13),
        (95, 'Manteniment electromecànic', 14),
        (96, 'Instal·lacions de producció de calor', 14),
        (97, 'Instal·lacions frigorífiques i de climatització', 14),
        (98, 'Manteniment d''instal·lacions tèrmiques i de fluids', 14),
        (99, 'Desenvolupament de projectes d''instal·lacions tèrmiques i de fluids', 14),
        (100, 'Mecatrònica industrial', 14),
        (101, 'Perruqueria i cosmètica capil·lar', 15),
        (102, 'Estètica i bellesa', 15),
        (103, 'Assessoria d''imatge personal i corporativa', 15),
        (104, 'Estètica integral i benestar', 15),
        (105, 'Estilisme i direcció de perruqueria', 15),
        (106, 'Caracterització i maquillatge professional', 15),
        (107, 'Vídeo, discjòquei i so', 16),
        (108, 'Realització de projectes d''audiovisuals i espectacles', 16),
        (109, 'Il·luminació, captació i tractament d''imatge', 16),
        (110, 'So per a audiovisuals i espectacles', 16),
        (111, 'Producció d''audiovisuals i espectacles', 16),
        (112, 'Animacions 3D, jocs i entorns interactius', 16),
        (114, 'Cultius Aqüícoles', 17),
        (115, 'Operacions subaquàtiques i hiperbàriques', 17),
        (116, 'Navegació i pesca de litoral', 17),
        (117, 'Manteniment i control de la maquinària de vaixells i embarcacions', 17),
        (118, 'Transport marítim i pesca d''altura', 17),
        (119, 'Aqüicultura', 17),
        (120, 'Organització del manteniment de la maquinària de vaixells i embarcacions', 17),
        (121, 'Planta química', 18),
        (122, 'Operacions de laboratori', 18),
        (123, 'Química industrial', 18),
        (124, 'Fabricació de productes farmacèutics, biotecnològics i afins', 18),
        (125, 'Laboratori d''anàlisi i control de qualitat', 18),
        (126, 'Operacions de procés de pasta i paper', 18),
        (127, 'Operacions de fabricació de productes farmacèutics', 18),
        (128, 'Indústries de procés de pasta i paper', 18),
        (129, 'Química ambiental', 18),
        (130, 'Farmàcia i parafarmàcia', 19),
        (131, 'Emergències sanitàries', 19),
        (132, 'Pròtesis dentals', 19),
        (133, 'Ortopròtesi i productes de suport', 19),
        (134, 'Anatomia patològica i citodiagnòstic', 19),
        (135, 'Documentació i administració sanitària', 19),
        (136, 'Documentació i administració sanitàries', 19),
        (137, 'Laboratori clínic i biomèdic', 19),
        (138, 'Radioteràpia i dosimetria', 19),
        (139, 'Audiologia protètica', 19),
        (140, 'Higiene bucodental', 19),
        (141, 'Imatge per al diagnòstic i medicina nuclear', 19),
        (142, 'Laboratori d''imatge', 19),
        (143, 'Cures auxiliars d''infermeria', 19),
        (144, 'Òptica d''ullera', 19),
        (145, 'Salut ambiental', 19),
        (146, 'Dietètica', 19),
        (147, 'Atenció a persones en situació de dependència', 20),
        (148, 'Animació sociocultural i turística', 20),
        (149, 'Educació Infantil', 20),
        (150, 'Integració social', 20),
        (151, 'Promoció d''igualtat de gènere', 20),
        (152, 'Mediació comunicativa', 20),
        (153, 'Emergències i protecció civil', 21),
        (154, 'Educació i control ambiental', 21),
        (155, 'Coordinació d''emergències i protecció civil', 21),
        (156, 'Electromecànica de vehicles automòbils', 22),
        (157, 'Carrosseria', 22),
        (158, 'Electromecànica de maquinària', 22),
        (159, 'Manteniment de material rodant ferroviari', 22),
        (160, 'Conducció de vehicles de transport per carretera', 22),
        (161, 'Manteniment d''embarcacions d''esbarjo', 22),
        (162, 'Automoció', 22),
        (163, 'Manteniment aeromecànic', 22),
        (164, 'Manteniment d''aviònica', 22),
        (165, 'Fabricació i ennobliment de productes tèxtils', 23),
        (166, 'Confecció i moda', 23),
        (167, 'Disseny tècnic en tèxtil i pell', 23),
        (168, 'Vestuari a mida i d''espectacles', 23),
        (169, 'Patronatge i moda', 23),
        (170, 'Ensenyament i animació socioesportiva', 24),
        (171, 'Condicionament físic', 24),
        (172, 'Prevenció de riscos professionals', 25);
    SQL;

        // Ejecutamos el SQL
        $pdo->exec($sql);

        echo "¡Seeder executat amb exit! S'han insertat les familias i els ciclos.\n";

    } catch (PDOException $e) {
        // missatges d'error
        echo "ERROR DE BASE DE DADES: " . $e->getMessage() . "\n";
    }
